tap "dart-lang/dart"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "readline", link: true
brew "awscli"
brew "bash"
brew "bazel"
brew "boost"
brew "python"
brew "cmake"
brew "cocoapods"
brew "colordiff"
brew "dmd"
brew "fontforge"
brew "gcc"
brew "git"
brew "go"
brew "googler"
brew "highlight"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "libusbmuxd", args: ["HEAD"]
brew "mercurial"
brew "minikube", link: false
brew "node"
brew "premake"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "rlwrap"
brew "ruby"
brew "rust"
brew "swig"
brew "telnet"
brew "the_silver_searcher"
brew "watch"
brew "yarn"
brew "zsh"
brew "dart-lang/dart/dart"
brew "github/gh/gh"
cask "aerial"
cask "docker"
cask "minikube"
cask "pusher"
cask "rabbitmq"
cask "redis"
cask "virtualbox"
